ParalympicProject/Paralympic2050/urls.py
from django.urls import path, re_path
import os, sys
from Paralympic2050 import views
from .views import RegisterPage, LoginPage, AthleteDisplay, LogoutView, VideoIntroPage

#### import the external pages
from .Django_external_views.homepage_view import HomePage
from .Django_external_views.Event_manage_view import EventManagement
from .Django_external_views.Medal_summary_view import MedalSummary
from .Django_external_views.Ticket_booking import TicketBooking
from .Django_external_views.shop import Shopping, AboutPage

#### Application name
app_name = "Paralympic2050"

urlpatterns = [
    ### Homepage
    path("", HomePage.as_view(), name="home"),

    #### Other pages
    path("register/", RegisterPage.as_view(), name="register"),
    path("login/", LoginPage.as_view(), name="login"),
    path("athletes/", AthleteDisplay.as_view(), name="athletes"),
    path("event/", EventManagement.as_view(), name = "event"),
    path("medals/", MedalSummary.as_view(), name = "medals"),
    path("ticket/", TicketBooking.as_view(), name = "ticket"),
    path("shop/", Shopping.as_view(), name = "shop"),
    path("video_intro/", VideoIntroPage.as_view(), name="kirito_intro"),
    path("about/", AboutPage.as_view(), name= "about"),


    ### logout reloading
    path("logout/", LogoutView.as_view(), name="logout"),
]

ParalympicProject/Paralympic2050/models.py
from django.db import models

#### This model is already connect to postgreSQL db
## I rename this model to athletes (you will see it in postgreSQL)
class Athletes(models.Model):
    bid = models.IntegerField()
    country = models.CharField(max_length=100)
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    gender = models.CharField(max_length=10)
    age = models.IntegerField(blank=True, null=True)
    dateOfBirth = models.DateField(null=True, blank=True)
    classification = models.CharField(max_length=50)
    imgProfile = models.URLField(max_length=255, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    class Meta:
        db_table  = "athletes" ###### I will rename the database table to athletes
        verbose_name = "Athlete"
        verbose_name_plural = "Athletes"

#### This is for the register sign up username and email storage
class UserData(models.Model):  #### This one will automatically turns into the form field (<input> in HTML)
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=128) 

    class Meta:
        db_table  = "userdatas"
        verbose_name = "userdata"
        verbose_name_plural = "userdatas" 

##### IN the event management I will use each model to represent
#### each event hosted... These will be put into the postgreSQL database
class Event(models.Model):
    date_time = models.DateTimeField(verbose_name="Date and Time")
    number = models.CharField(max_length=10, verbose_name="Event No.")
    gender = models.CharField(max_length=10)
    sport = models.CharField(max_length=100)
    classification = models.CharField(max_length=10)
    phrase = models.CharField(max_length=20)
    status = models.CharField(max_length=20)
    location = models.CharField(max_length=255, null=True, blank=True) # <-- เพิ่มบรรทัดนี้

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["date_time"]
        db_table  = "sport_events"
        verbose_name = "sport_event"
        verbose_name_plural = "sport_events"

##### THis one is the Medals model which collects the data of team name
#### gold, silver and bronze medal
class Medal(models.Model):
    team = models.CharField(max_length=100)
    gold = models.PositiveIntegerField(default=0)
    silver = models.PositiveIntegerField(default=0)
    bronze = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField(default=0)

    class Meta:
        db_table = "medal_summary"   
        verbose_name = "medal"      
        verbose_name_plural = "medals"  

##### The ticket class, when user buys the ticket
class Ticket(models.Model):
    user = models.ForeignKey(UserData, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    category = models.CharField(max_length=1, choices=[("A", "Category A"), ("B", "Category B")])
    ticket_type = models.CharField(max_length=50)
    quantity = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    visa_last_four = models.CharField(max_length=4, blank=True, null=True)  
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "ticket"   
        verbose_name = "tickets"      
        verbose_name_plural = "ticket_value"  

ParalympicProject/Paralympic2050/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import path, re_path, reverse
from django.http import HttpResponse, HttpRequest, JsonResponse, \
    HttpResponseRedirect, HttpResponseBadRequest
from datetime import date, datetime
from django.template import loader
from django.views import View
from django.views.generic import ListView, list
import csv
from .models import Athletes, UserData
from django.contrib import messages
import numpy as np
import json
from django.contrib.auth import authenticate, logout, login
from django.http import JsonResponse
from django.db.models import Q ### I think this is for the query
import sys, os

######## (This is how to get the latest version of code in github)
####### git fetch origin
######## git reset --hard origin/main

###### importing the external pages
from .Django_external_views.homepage_view import HomePage

############## Register page
class RegisterPage(View): #### This is like GET and POST method in HTML forms handling
    def get(self, request):
        return render(request, "Registering/register.html")

    def post(self, request):
        username =  request.POST.get("username").strip()
        password = request.POST.get("password")
        conpass = request.POST.get("conpass")

        ##### I have created the admin account
        #### This method will prevetnt from registering into admin account
        if username.lower() == "admin":
            return render(request, "Registering/register.html", {
                "username_taken": True,
                "taken_username": username,
                "reserved_name": True,
                "err": "DO NOT USE THE ADMIN ACCOUNT"  
            })

        ### Already exist username
        if UserData.objects.filter(username=username).exists():
            data = {
                "username_taken": True,
                "taken_username": username
            }
            return render(request, "Registering/register.html", data)

        if (password is None) or (password != conpass):
            cont = {
                "password_mismatch": True,
                "err": "Password not match",
            }
            return render(request, "Registering/register.html", cont)
      
        ###### When the username is same
        if UserData.objects.filter(username__iexact=username).exists():
            return render(request, "Registering/register.html", {
                "username_taken": True,
                "taken_username": username
            })
        
        ##### Saving thje username to the db
        UserData.objects.create(username = username, password = password)
        
        return redirect("Paralympic2050:login")

############ The login page
class LoginPage(View):
    def get(self, request):
        return render(request, "Registering/login.html")
    
    def post(self, request):
        username = request.POST.get("username").strip()
        password = request.POST.get("password")

        if not UserData.objects.filter(username=username).exists():
            datas = {
                "username_not_exist": True, 
                "entered_username": username,
                "not_exist": True,           
                "enter_user": username
            }
            #### Failed to login, return to the same page
            return render(request, "Registering/login.html", datas)

        try:
            user = UserData.objects.get(username__iexact=username)
        except UserData.DoesNotExist:
            return render(request, "Registering/login.html", {
                "not_exist": True,
                "enter_user": username,
            })

        if user.password != password:
            return render(request, "Registering/login.html", {
                "wrong_password": True,
                "entered_username": username,
            })
        
        #### stored inside the session variable (it can be called in any page)
        request.session['logged_in_user'] = user.username

        #### Admin account and permission
        if username.lower() == "admin":
            request.session["is_admin"] = True
        else:
            request.session["is_admin"] = False

        ### Detect whether the user name is kirito, if kirito 
        #### something good will happen (The video kirito will show)
        if username.lower() == "kirito":
            request.session["show_video"] = True
            return redirect("Paralympic2050:kirito_intro")
        
        return redirect("Paralympic2050:home") ### After login, go to the home page

#### This will show if user login as kirito
### this is the video views 'Link Start'
class VideoIntroPage(View):
    def get(self, request):
        if not request.session.get("show_video", False):
            return redirect("Paralympic2050:home")
        
        del request.session["show_video"]
        return render(request, "Registering/kirito_intro.html")
    

########### Athlete display page
class AthleteDisplay(ListView):
    temp = "Displaying/Athletes_display.html"
    
    def get(self, request, *args, **kwargs):
        ###### This is for the search features
        key = request.GET.get("keyword", "").strip()
        gender = request.GET.get("gender", "").strip()

        athletes = Athletes.objects.all()

        if key:
           athletes = athletes.filter(
               Q(firstName__icontains=key) | Q(lastName__icontains=key)
           )
        
        if gender and gender.lower() != "all":
            athletes = athletes.filter(gender__iexact = gender)

        if gender:
            athletes = athletes.filter(gender__iexact=gender)

        ath_dictionary = {"athletes": athletes, "keyword": key, "gender": gender}
        return render(request, self.temp, ath_dictionary)
    
class AthleteDisplay(ListView):
    temp = "Displaying/Athletes_display.html"

    def get(self, request, *args, **kwargs): #### This will works for search and filter in django
        key = request.GET.get("keyword", "").strip()
        gender = request.GET.get("gender", "").strip()

        athletes = Athletes.objects.all().order_by("firstName", "lastName")  # Alphabetical sorting

        if key:
           athletes = athletes.filter(
               Q(firstName__icontains=key) | Q(lastName__icontains=key)
           )
        
        if gender and gender.lower() != "all":
            athletes = athletes.filter(gender__iexact=gender)

        ath_dictionary = {"athletes": athletes, "keyword": key, "gender": gender}
        return render(request, self.temp, ath_dictionary)
    
        
    def post(self, request, *args, **kwargs):
        #### Check whether the user is admin or not
        if request.session.get("logged_in_user") != "admin":
            messages.error("No permission to edit, delete and add")
            return redirect("Paralympic2050:athletes")

        #### Delete selected athletes 
        delete_ids = request.POST.getlist("delete_ids")

        if delete_ids:
            Athletes.objects.filter(id__in=delete_ids).delete()
            messages.success(request, f"Deleted {len(delete_ids)} athlete(s).")
            athletes = Athletes.objects.all().order_by('firstName', 'lastName')
            return render(request, self.temp, {"athletes": athletes})

        ####### Edit the athlete information
        athlete_id = request.POST.get("athlete_id")
        
        if athlete_id:
            athlete = get_object_or_404(Athletes, id=athlete_id)
            athlete.firstName = request.POST.get("firstName", athlete.firstName)
            athlete.lastName = request.POST.get("lastName", athlete.lastName)
            athlete.gender = request.POST.get("gender", athlete.gender)
            
            if request.POST.get("age"):
                athlete.age = request.POST.get("age")
            athlete.save()
            messages.success(request, "Successfully updated")

        ####### Add new athlete into the database
        bib = request.POST.get("bib")
        classification = request.POST.get("classification")
        country = request.POST.get("country")
        first_name = request.POST.get("first_name")
        surname = request.POST.get("surname")
        gender = request.POST.get("gender")
        email = request.POST.get("email")
        dob = request.POST.get("date_of_birth")

        if (bib and classification and country and first_name and surname):
            new_athlete = Athletes.objects.create(
                bid=bib,
                classification=classification,
                country=country,
                firstName=first_name,
                lastName=surname,
                gender=gender,
                email= email if email else None,
                dateOfBirth = dob,
            )
            messages.success(request, f"Athlete {first_name} {surname} added")

        ##### Now this will filter athletes orderby alphabetical order
        athletes = Athletes.objects.all().order_by("firstName", "lastName")
        return redirect("Paralympic2050:athletes")

##### Logged out view
class LogoutView(View):
    def post(self, request):
        print("Before logout: {}".format( request.session.get('logged_in_user')))
        
        logout(request) 
        request.session.pop("logged_in_user", None)

        if "logged_in_user" in request.session:
            del request.session['logged_in_user']
        
        print("After logout: {}".format(request.session.get('logged_in_user')))
            
        return JsonResponse({"status": "logged out"})

###### Homepage, this page is actually inside another folder.
### This is just an class instance (the real homepage is in Django_exteral_veiws)
class Home2(View):
    def get(self, request, *args, **kwargs):
        homepage = HomePage()
        return homepage.get(request)

###### This is the end of the code of the views.py
#### For further, I've created a external view in Django_external_views folder

ParalympicProject/Paralympic2050/templates/Registering/Login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Paralympic2050</title>

    {% load static %} 
    {% block style %}
        <link rel="stylesheet" href="{% static 'css_file/login.css' %}?v=1.0">
        <link rel="icon" type="image/png" href="{% static 'img/login_register_img/IPC_logo.png'%}">
    {% endblock %}
</head>
<body>
    <!--The PAGE bg-->
    <div class="page-bg">
        <img src="{% static 'img/login_register_img/bg_register.png' %}" alt="ParalympicBg">
    </div> 

    <section>
        <div class="paralympic-logo">
            <img src="{% static 'img/login_register_img/IPC_logo2white.png' %}" width="550px" alt="Paralympic Logo">
        </div>
    </section>

    <section>
        <div class="login-cont">
            <h1>Login as Admin</h1>
            
            <!--Login forms-->
            <form method="post" id="login-form">
                {% csrf_token %}
                <input type="text" name="username" id="username" placeholder="Enter your email or username" required>
                <input type="password" name="password" id="password" placeholder="Enter your password" required>

                <div class="remember-and-forgot">
                    <label for="remember" class="remember">
                        <input type="checkbox" id="remember" name="remember" value="remember">
                        <span>Remember me</span>
                    </label>
                    <a href="">Forgot your password?</a>
                </div>

                <div class="login-submission">
                    <button type="submit" class="login-btn">Login</button>
                </div>
                
                <!--When username not exist, show this paragraph-->
                {% if not_exist %}
                    <p id="username-error" style="color:red; font-weight:bold;">
                        Username "{{ enter_user }}" does not exist.
                    </p>
                {% endif %}
                
                <!--wrong username or wrong pass-->
                {% if wrong_password %}
                    <p id="wrong-form" style="color:red; font-weight:bold;">
                        Username or password incorrect
                    </p>
                {% endif %}

                <!--Wrong username or pwd-->
                <input type="hidden" id="wrong-pass" value="{% if wrong_password %}1{% else %}0{% endif %}">
                <input type="hidden" id="username-not-exist" value="{% if username_not_exist %}1{% else %}0{% endif %}">
                <input type="hidden" id="entered-username" value="{{ entered_username|default:'' }}">     
            </form>

            <div class="social-media-login">
                <button class="google-btn-login">
                    <img src="{% static 'img/login_register_img/search.png' %}" alt="Google" width="20px" class="btn-icon">
                    Login with Google
                </button>

                <button class="facebook-btn-login">
                    <img src="{% static 'img/login_register_img/communication.png' %}" alt="Facebook" width="20px" class="btn-icon">
                    Login with Facebook
                </button>
            </div>

            <p class="dont-acc">Don't have an account? <a href="{% url 'Paralympic2050:register' %}">Sign up</a></p>
        </div>
    </section>

<!--JS file inside the statics JS_file path-->
<script src="{% static 'js_file/login.js' %}"></script>

</body>
</html>

ParalympicProject/Paralympic2050/templates/Registering/Register.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Paralympic2050</title>

        {% load static %} 
        {% block style %}
            <link rel="stylesheet" href="{% static 'css_file/register.css' %}?v=1.0">
            <link rel="icon" type = "image/png" href="{% static 'img/login_register_img/IPC_logo.png'%}">

            <!--The font link from google fonts-->
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Hammersmith+One&display=swap" rel="stylesheet">
            
        {% endblock %}
    </head>
<body>
    <div class = "page-bg">
        <img src = "{% static 'img/login_register_img/bg_register.png' %}" alt = "ParalympicBg">
    </div> 

    <section>
        <div class = "paralympic-logo">
            <img src = "{% static 'img/login_register_img/IPC_logo2white.png' %}" width="550px" alt = "ParalympicBg">
        </div>
    <section>

    <section>
        <div class = "register-cont">
            <h1>Sign Up as Admin</h1>
            
            <!-- Create the register forms -->
            <form method="post" id="register-form">
                {% csrf_token %}
                <input type="text" name="username" id="username" placeholder="Enter your email or username" required>
                <input type="password" name="password" id="password" placeholder="Enter your password" required>
                <input type="password" name="conpass" id="conpass" placeholder="Confirm your password" required>

                <div class="submit-ctn">
                    <button type="submit" class="signup-btn">Sign up</button>
                </div>
            </form>
            
            <!--Username taken and taken username-->
            <input type="hidden" id="username_taken" value="{{ username_taken|default:False }}">
            <input type="hidden" id="taken_username" value="{{ taken_username|default:'' }}">
            <input type="hidden" id="password_mismatch" value="{{ password_mismatch|default:False }}">

            <hr>
            <div class="social-media">
                <button class="google-btn">
                    <img src="{% static 'img/login_register_img/search.png' %}" alt="Google" width= "20px" class="btn-icon">
                    Sign up with Google
                </button>

                <button class="facebook-btn">
                    <img src="{% static 'img/login_register_img/communication.png' %}" alt="Facebook" width="20px" class="btn-icon">
                    Sign up with Facebook
                </button>
            </div>

            <p class="alr-acc">Already have an account? <a href="{% url 'Paralympic2050:login' %}">Login</a></p>
        </div>
    <section>

<!--JavaScript-->
<script src="{% static 'js_file/register.js' %}"></script>

</body>
</html>

ParalympicProject/Paralympic2050/templates/Registering/kirito_intro.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Paralympic2050: LINK START!!!</title>

    {% block css_style %}
        <link rel="stylesheet" href="{% static 'css_file/kirito_intro.css' %}?v=1.0">
        <link rel="icon" type = "image/png" href="{% static 'img/login_register_img/IPC_logo.png'%}">
    {% endblock %}
</head>
<body>
    <section class="video-section">
        <video class="video-play" autoplay>
            <source src="{% static 'img/videos/LinkStart.mp4' %}" type="video/mp4">
        </video>
    </section>

    <script>
        const video = document.querySelector(".video-play");

        const audioContext = new (window.AudioContext || window.webkitAudioContext)();
        const source = audioContext.createMediaElementSource(video);
        const gainNode = audioContext.createGain();
        source.connect(gainNode);
        gainNode.connect(audioContext.destination);

        gainNode.gain.value = 1.0;

        video.addEventListener("click", function () {
            if (video.muted) {
                video.muted = false;
                audioContext.resume();
            } 
            else {
                video.muted = true;
            }
            video.play();
        });

        video.addEventListener("ended", function () {
            window.location.href = "{% url 'Paralympic2050:home' %}";
        });
    </script>
</body>
</html>